# Cache pre-commit hooks for better performance
default_language_version:
  python: python3
  rust: stable
  golang: "1.21"
  node: system

# Simplified exclude pattern
exclude: >-
  (?x)^(
    \.direnv/|
    target/|
    dist/|
    result|
    \.git/|
    \.terraform/|
    \.terragrunt-cache/|
    devenv/
  )

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
        exclude: ^\.pre-commit-config\.yaml$  # Exclude this file from end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: detect-aws-credentials
      - id: check-json

  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.96.2  # Use the latest stable version
    hooks:
      - id: terraform_fmt
        name: Terraform Format
        description: Automatically format Terraform code
      - id: terragrunt_fmt
        name: Terragrunt Format
        description: Automatically format Terragrunt HCL files

# Global settings
minimum_pre_commit_version: "3.0.0"
ci:
  autofix_commit_msg: "style: auto-format pre-commit hooks"
  autoupdate_commit_msg: "chore: pre-commit autoupdate"
  skip: [treefmt, rustfmt, yamllint]
