---
# Cache pre-commit hooks for better performance
default_language_version:
  python: python3
  rust: stable
  golang: '1.21'
  node: system
# Global exclude pattern (if necessary)
exclude: >-
  (?x)^(
    \.direnv/|
    target/|
    dist/|
    result|
    \.git/|
    \.terraform/|
    \.terragrunt-cache/|
    devenv/|
    node_modules/|
    vendor/|
    \.github/ISSUE_TEMPLATE/|
    .github/workflows/|
    tests/testdata/|
    \.goreleaser\.yaml
  )
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: detect-aws-credentials
      - id: check-json
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.96.2
    hooks:
      - id: terraform_fmt
      - id: terragrunt_fmt
  # Updated yamlfmt hook
  - repo: https://github.com/google/yamlfmt
    rev: v0.14.0
    hooks:
      - id: yamlfmt
        language: system
        additional_dependencies: []
        args:
          - -conf=.yamlfmt.yml
        files: \.(yml|yaml)$
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.35.1
    hooks:
      - id: yamllint
        args: [-c=.yamllint.yml]
        files: \.(yml|yaml)$
        exclude: >-
          (?x)^(
            \.github/workflows/|
            tests/testdata/|
            \.goreleaser\.yaml|
            \.markdownlint\.yaml
          )
# Global settings
minimum_pre_commit_version: 3.0.0
ci:
  autofix_commit_msg: 'style: auto-format pre-commit hooks'
  autoupdate_commit_msg: 'chore: pre-commit autoupdate'
  skip: [treefmt, rustfmt]
