# Cache pre-commit hooks for better performance
default_language_version:
  python: python3
  rust: stable
  golang: "1.21"

# Skip these files/directories for all hooks
exclude: |
  (?x)(
    ^(.direnv/.*)|
    ^(target/.*)|
    ^(dist/.*)|
    ^(result.*)|
    ^(.git/.*)|
    ^(.terraform/.*)|
    ^(.terragrunt-cache/.*)|
    ^(devenv/.*)
  )

repos:
  - repo: meta
    hooks:
      - id: check-hooks-apply
      - id: check-useless-excludes
      - id: identity 

  - repo: local
    hooks:
      - id: treefmt
        name: Format files using treefmt
        entry: treefmt
        language: system
        pass_filenames: true
        types_or: [go, rust, terraform, yaml, json, markdown, nix]
        stages: [pre-commit]

      - id: rustfmt
        name: Format Rust code
        entry: rustfmt
        language: system
        pass_filenames: true
        types: [rust]
        stages: [pre-commit]
        args: ["--edition=2021"]

      - id: golangci-lint
        name: Lint Go code
        entry: golangci-lint run
        language: system
        pass_filenames: true
        types: [go]
        stages: [pre-commit]
        args: [
          "--fast",
          "--max-same-issues=0",
          "--max-issues-per-linter=0",
          "--modules-download-mode=readonly"
        ]

      - id: yamllint
        name: Lint YAML files
        entry: yamllint
        language: system
        pass_filenames: true
        types: [yaml]
        stages: [pre-commit]
        args: ["--strict"]

# Global settings
minimum_pre_commit_version: "3.0.0"
ci:
  autofix_commit_msg: "style: auto-format pre-commit hooks"
  autoupdate_commit_msg: "chore: pre-commit autoupdate"
  skip: [treefmt, rustfmt, golangci-lint, yamllint]
