# Cache pre-commit hooks for better performance
default_language_version:
  python: python3
  rust: stable
  golang: "1.21"
  node: system

# Skip these files/directories for all hooks
exclude: |
  (?x)(
    ^(.direnv/.*)|
    ^(target/.*)|
    ^(dist/.*)|
    ^(result.*)|
    ^(.git/.*)|
    ^(.terraform/.*)|
    ^(.terragrunt-cache/.*)|
    ^(devenv/.*)
  )

repos:
  - repo: meta
    hooks:
      - id: check-hooks-apply
      - id: check-useless-excludes

  - repo: local
    hooks:
      - id: check-useless-excludes
        name: Check for useless excludes
        entry: check-useless-excludes
        language: system
        pass_filenames: false

      - id: treefmt
        name: treefmt
        entry: treefmt
        language: system
        types_or: [file]
        pass_filenames: true

      - id: yamlfmt
        name: yamlfmt
        entry: yamlfmt
        language: system
        types: [yaml]
        args: []

      - id: golangci-lint
        name: golangci-lint
        entry: golangci-lint run
        language: system
        types: [go]

# Global settings
minimum_pre_commit_version: "3.0.0"
ci:
  autofix_commit_msg: "style: auto-format pre-commit hooks"
  autoupdate_commit_msg: "chore: pre-commit autoupdate"
  skip: [treefmt, rustfmt, golangci-lint, yamllint]