---
version: '3'

dotenv: ['.env.{{.ENV}}.aws', '.env.{{.ENV}}.terraform', '.env.{{.ENV}}.terragrunt']
vars:
    mod:
    fn:

includes:
    dx:
        taskfile: ./taskfiles/taskfile.dx.yml
    precommit:
        taskfile: ./taskfiles/taskfile.precommit.yml
    dagger:
        taskfile: ./taskfiles/Taskfile.dagger.yml

tasks:
    default:
        cmds:
            - task: dx:default
    pc-init:
        desc: Initialize and install required hooks
        cmds:
            - task: precommit:hooks-init
    pc-run:
        desc: Run all the hooks described in the .pre-commit-config.yaml file
        cmds:
            - task: precommit:hooks-run
    iac-terragrunt-ci:
        desc: Run CI in the go code for the 'iac-terragrunt' module
        cmds:
            - task: mod_iac_terragrunt:mod-ci

    # Dagger specific tasks.
    mod-sync:
        desc: Sync the dagger module
        cmds:
            - task: dagger:sync
              vars: {module: '{{.mod}}'}

    mod-sync-all:
        desc: Sync all the dagger modules
        cmds:
            - ./scripts/dagger-sync.sh

    mod-publish:
        desc: Publish the dagger module
        cmds:
            - task: dagger:publish
              vars: {module: '{{.mod}}'}

    mod-list-docs:
        cmds:
            - |
              cat <<-EOT
                  # List all the functions in the dagger module
                  # ---------------------------------------------------------------
                  #
                  # It executes the equivalent of: dagger functions -m {{.mod}}
                  #
                  # Example:
                  # task mod-list-functions mod=<my-module-path/github-repo>
                  #
                  # ---------------------------------------------------------------
              EOT
        silent: true

    mod-list:
        deps: [mod-list-docs, mod-sync]
        desc: List all the functions in the dagger module
        cmds:
            - task: dagger:list-functions
              vars: {module: '{{.mod}}'}

    mod-exec-docs:
        cmds:
            - |
              cat <<-EOT
                  # Run a function in the dagger module
                  # ---------------------------------------------------------------
                  # It executes the equivalent of: dagger call -m {{.mod}} {{.fn}} -- --help
                  # It propagates the CLI_ARGS variable to the dagger call command
                  #
                  # Example:
                  # task mod-exec-docs mod=<my-module-path/github-repo> fn=<my-function-name> -- <flags>
                  # ---------------------------------------------------------------
              EOT
        silent: true

    mod-exec:
        deps: [mod-exec-docs, mod-sync]
        desc: Run a function in the dagger module
        cmds:
            - task: dagger:call
              vars: {module: '{{.mod}}', function: '{{.fn}}'}
