---
version: '3'

dotenv: ['.env.{{.ENV}}.aws', '.env.{{.ENV}}.terraform', '.env.{{.ENV}}.terragrunt']

includes:
    dx:
        taskfile: ./taskfiles/taskfile.dx.yml
    precommit:
        taskfile: ./taskfiles/taskfile.precommit.yml

    # Include dagger modules's tasks.
    mod_iac_terragrunt:
        taskfile: ./iac-terragrunt/TaskFile.yml

tasks:
    default:
        cmds:
            - task: dx:default
    pc-init:
        desc: Initialize and install required hooks
        cmds:
            - task: precommit:hooks-init
    pc-run:
        desc: Run all the hooks described in the .pre-commit-config.yaml file
        cmds:
            - task: precommit:hooks-run
    iac-terragrunt-ci:
        desc: Run CI in the go code for the 'iac-terragrunt' module
        cmds:
            - task: mod_iac_terragrunt:mod-ci
