exclude_patterns = ["*/internal/*", "dagger.gen.go"]

check_before_format = true

[formatter]
# Specify formatters with their includes
[formatter.gofmt]
command = "gofmt"
includes = ["*.go"]

[formatter.rustfmt]
command = "rustfmt"
includes = ["*.rs"]

[formatter.alejandra]
command = "alejandra"
includes = ["*.nix"]

[formatter.prettier]
command = "prettier --write"
include = ["**/*.{js,jsx,ts,tsx,json,md,markdown,yaml,yml}"]

[formatter.terraform-fmt]
command = "terraform fmt -"
include = ["**/*.tf"]

[formatter.terragrunt-fmt]
command = "terragrunt hclfmt"
include = ["**/*.hcl"]
