[package]
name = "daggy"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.7", features = ["derive"] }
serde = { version = "1.0.203", features = ["derive"] }
regex = "1.10.5"
serde_json = "1.0.121"
pathdiff = "0.2.1"
walkdir = "2.3.3"
similar = "2.2.1"
