---
version: "1.0"
# Global settings applied to all resources unless overridden
global:
  enabled: true
  batch_size: 20
  tag_criteria:
    compliance_level: standard

# Resource-specific configurations
resources:
  s3:
    enabled: true
    batch_size: 10
    tag_criteria:
      compliance_level: high
    excluded_resources:
      - pattern: terraform-state-*
        reason: Terraform state buckets managed separately
      - pattern: log-archive-*
        reason: Logging buckets excluded from standard compliance

# Compliance levels and their requirements
compliance_levels:
  high:
    required_tags:
      - SecurityLevel
      - DataClassification
      - Backup
      - Owner
      - CostCenter
    specific_tags:
      SecurityApproved: "true"
      MonitoringEnabled: "true"
  standard:
    required_tags:
      - Owner
      - Project
      - Environment
    specific_tags:
      MonitoringEnabled: "true"

# Tag validation rules
tag_validation:
  allowed_values:
    Environment:
      - production
      - staging
      - development
    DataClassification:
      - public
      - private
      - confidential
    SecurityLevel:
      - high
      - medium
      - low
  pattern_rules:
    CostCenter: ^[A-Z]{2}-[0-9]{4}$
    ProjectCode: ^PRJ-[0-9]{5}$

# Notification settings for non-compliant resources
notifications:
  slack:
    enabled: true
    channels:
      high_priority: compliance-alerts
      standard: compliance-reports
  email:
    enabled: true
    recipients:
      - cloud-team@company.com
      - security-team@company.com
