---
version: '3'
env:
    WORKDIR: iac-terragrunt
    GOLANGCI_LINT_CONFIG_FILE: ../.golangci.yml
includes:
    gotasks:
        taskfile: ../taskfiles/Taskfile.go.yml
    dagger:
        taskfile: ../taskfiles/Taskfile.dagger.yml
tasks:
    mod-ci:
        desc: Tidy go modules
        dir: '{{.WORKDIR}}'
        cmds:
            - task: dagger:sync
            - task: gotasks:inspect-workdir
            - task: gotasks:go-ci
              vars:
                  GOLANGCI_LINT_CONFIG_FILE: '{{.GOLANGCI_LINT_CONFIG_FILE}}'
