contents:
  repositories:
    - https://dl-cdn.alpinelinux.org/alpine/v3.18/main
    - https://dl-cdn.alpinelinux.org/alpine/v3.18/community
  packages:
    - alpine-baselayout
    - alpine-keys
    - apk-tools
    - ca-certificates-bundle
    - musl
    - curl
    - bash
    - git
    - openssl
accounts:
  groups:
    - groupname: tflinter
      gid: 65532
  users:
    - username: tflinter
      uid: 65532
      gid: 65532
  run-as: tflinter
entrypoint:
  command: /bin/bash -l
archs:
  - x86_64
  - aarch64
environment:
  PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/home/tflinter/bin:/home/tflinter/.local/bin
  TZ: UTC
  LANG: en_US.UTF-8
  LC_ALL: en_US.UTF-8
paths:
  - path: /home/tflinter
    type: directory
    uid: 65532
    gid: 65532
    permissions: 0o755
  - path: /home/tflinter/bin
    type: directory
    uid: 65532
    gid: 65532
    permissions: 0o755
  - path: /home/.terraform.d/plugin-cache
    type: directory
    uid: 65532
    gid: 65532
    permissions: 0o755
  - path: /home/.terraform.d/plugins
    type: directory
    uid: 65532
    gid: 65532
    permissions: 0o755
  - path: /home/.terraform.d/providers
    type: directory
    uid: 65532
    gid: 65532
    permissions: 0o755
  # Default /mnt directory
  - path: /mnt
    type: directory
    uid: 65532
    gid: 65532
    permissions: 0o755
annotations:
  title: Base Alpine for TFLinter
  description: A minimal Alpine base image built with APKO for TFLinter, optimized for security and performance.
  version: 1.1.0
  vendor: github.com/Excoriate - Alex Torres
  licenses: Apache-2.0
  url: https://github.com/Excoriate/daggerverse
  source: https://github.com/Excoriate/daggerverse
