---
contents:
  repositories:
    - https://dl-cdn.alpinelinux.org/alpine/edge/main
    - https://dl-cdn.alpinelinux.org/alpine/edge/community
  packages:
    - alpine-base
    - ca-certificates
    - bash
    - curl
    - git
    - tzdata
    - wget

cmd: ["/bin/bash", "-l"]

archs:
  - x86_64
  - aarch64

environment:
  PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
  TERRAGRUNT_PROVIDER_CACHE_DIR: /root/.terragrunt-cache
  TERRAGRUNT_PROVIDER_CACHE: "1"
  TZ: UTC
  LANG: en_US.UTF-8
  LC_ALL: en_US.UTF-8

accounts:
  groups:
    - groupname: terragrunt
      gid: 1000
  users:
    - username: terragrunt
      uid: 1000

annotations:
  title: "Base Alpine for Terragrunt"
  description: "A minimal Alpine base image built with APKO for Terragrunt, optimized for security and performance."
  version: "1.1.0"
  vendor: "github.com/Excoriate - Alex Torres"
  licenses: "Apache-2.0"
  url: "https://github.com/Excoriate/daggerverse"
  source: "https://github.com/Excoriate/daggerverse"

sbom:
  enabled: true
  format: "spdx-json"

seccomp:
  policy: default

capabilities:
  drop:
    - ALL
