name: CI Templates 🧰
on:
  push:
    branches:
      - main
      - master
    paths:
      - "module-template/**"
      - "module-template-light/**"
  pull_request:
    paths:
      - "module-template/**"
      - "module-template-light/**"
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: read
  checks: write

env:
  GO_VERSION: "1.22"
  DAGGER_VERSION: "0.14.0"

jobs:
  dagger-build:
    strategy:
      matrix:
        module: [module-template, module-template-light]
      fail-fast: true
    name: 🏗️ Build ${{ matrix.module }} with Dagger ${{ env.DAGGER_VERSION }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: 📦 Dagger Develop Main Module
        uses: dagger/dagger-for-github@v6
        with:
          verb: develop
          module: ${{ matrix.module }}
          version: ${{ env.DAGGER_VERSION }}
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 🧪 Dagger Develop Test Module
        uses: dagger/dagger-for-github@v6
        with:
          verb: develop
          module: ${{ matrix.module }}/tests
          version: ${{ env.DAGGER_VERSION }}
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 📄 Dagger Develop Examples Module
        uses: dagger/dagger-for-github@v6
        with:
          verb: develop
          module: ${{ matrix.module }}/examples/go
          version: ${{ env.DAGGER_VERSION }}
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  dagger-call:
    needs: dagger-build
    strategy:
      matrix:
        module: [module-template, module-template-light]
      fail-fast: false
    name: 📞 Call Functions in ${{ matrix.module }} with Dagger ${{ env.DAGGER_VERSION }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: 📦 List Main Module Functions
        uses: dagger/dagger-for-github@v6
        with:
          verb: call
          module: ${{ matrix.module }}
          version: ${{ env.DAGGER_VERSION }}
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 🧪 List Test Module Functions
        uses: dagger/dagger-for-github@v6
        with:
          verb: call
          module: ${{ matrix.module }}/tests
          version: ${{ env.DAGGER_VERSION }}
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 📄 List Example Module Functions
        uses: dagger/dagger-for-github@v6
        with:
          verb: call
          module: ${{ matrix.module }}/examples/go
          version: ${{ env.DAGGER_VERSION }}
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  run-tests:
    needs: dagger-build
    strategy:
      matrix:
        module: [module-template, module-template-light]
      fail-fast: false
    name: 🧪 Run Tests for ${{ matrix.module }} with Dagger ${{ env.DAGGER_VERSION }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: 💣 Run All Tests
        uses: dagger/dagger-for-github@v6
        with:
          verb: call
          args: test-all
          module: ${{ matrix.module }}/tests
          version: ${{ env.DAGGER_VERSION }}
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  run-recipes:
    needs: dagger-build
    strategy:
      matrix:
        module: [module-template, module-template-light]
      fail-fast: false
    name: 🥗 Run Recipes for ${{ matrix.module }} with Dagger ${{ env.DAGGER_VERSION }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: 🥗 Run All Example Recipes
        uses: dagger/dagger-for-github@v6
        with:
          verb: call
          args: all-recipes
          module: ${{ matrix.module }}/examples/go
          version: ${{ env.DAGGER_VERSION }}
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
