name: CI module-template 🧹

env:
  DAGGER_VERSIONS: '["0.13.0", "0.13.1", "0.13.2", "0.13.3"]'
  DAGGER_LATEST_VERSION: "0.13.3"

on:
  push:
    branches:
      - main
      - master
    paths:
      - module-template/**/*.go
  pull_request:
    paths:
      - module-template/**/*.go
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: read
  checks: write

defaults:
  run:
    working-directory: module-template

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      dagger_versions: ${{ steps.set-matrix.outputs.dagger_versions }}
    steps:
      - id: set-matrix
        run: echo "dagger_versions=${{ env.DAGGER_VERSIONS }}" >> $GITHUB_OUTPUT

  dagger-linter:
    needs: setup
    strategy:
      matrix:
        go: ["1.22"]
        dagversion: ${{ fromJson(needs.setup.outputs.dagger_versions) }}
    name: Lint module-template on ${{ matrix.os }} with Dagger ${{ matrix.dagversion }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
      - name: Dagger Develop on Module 📦 with Dagger ${{ matrix.dagversion }}
        uses: dagger/dagger-for-github@v6
        with:
          verb: develop
          module: module-template
          version: ${{ matrix.dagversion }}
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # ... (rest of the steps for this job remain the same)

  golangci-lint:
    strategy:
      matrix:
        go: ["1.22"]
    name: GolangCI-Lint for module-template
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
      - name: Dagger Develop on Module 📦 module-template with Dagger ${{ env.DAGGER_LATEST_VERSION }}
        uses: dagger/dagger-for-github@v6
        with:
          verb: develop
          module: module-template
          version: ${{ env.DAGGER_LATEST_VERSION }}
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # ... (rest of the steps for this job remain the same)

  module-test:
    needs: setup
    strategy:
      matrix:
        go: ["1.22"]
        dagversion: ${{ fromJson(needs.setup.outputs.dagger_versions) }}
    name: Run Tests 🧪 in module-template on ${{ matrix.os }} with Dagger ${{ matrix.dagversion }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
      - name: Dagger Develop on Module 📦 with Dagger ${{ matrix.dagversion }}
        uses: dagger/dagger-for-github@v6
        with:
          verb: develop
          module: module-template
          version: ${{ matrix.dagversion }}
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # ... (rest of the steps for this job remain the same)

  module-template-recipes-go:
    strategy:
      matrix:
        go: ["1.22"]
    name: Run recipes 🥗 in module-template/examples/go on ${{ matrix.os }} with Dagger ${{ env.DAGGER_LATEST_VERSION }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
      - name: Dagger Develop on Module Examples 📄 with Dagger ${{ env.DAGGER_LATEST_VERSION }}
        uses: dagger/dagger-for-github@v6
        with:
          verb: develop
          module: module-template/examples/go
          version: ${{ env.DAGGER_LATEST_VERSION }}
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # ... (rest of the steps for this job remain the same)
