---
name: CI gotest 🧹
on:
  push:
    branches:
      - main
      - master
    paths:
      - gotest/**/*.go
  pull_request:
    paths:
      - gotest/**/*.go
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: read
  checks: write

defaults:
  run:
    working-directory: gotest

env:
  DAGGER_VERSION_EXAMPLES_GO: 0.13.7

jobs:
  dagger-linter:
    strategy:
      matrix:
        go: ["1.22"]
        dagversion: [0.13.7]
    name: Lint gotest on ${{ matrix.go }} with Dagger ${{ matrix.dagversion }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
      - name: Dagger Develop on Module 📦 with Dagger ${{ matrix.dagversion }}
        uses: dagger/dagger-for-github@v6
        with:
          verb: develop
          module: gotest
          version: ${{ matrix.dagversion }}
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Dagger Develop on Test Module 🧪 with Dagger ${{ matrix.dagversion }}
        uses: dagger/dagger-for-github@v6
        with:
          verb: develop
          module: gotest/tests
          version: ${{ matrix.dagversion }}
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Dagger Develop on Examples Module for Go 📄 with Dagger ${{ matrix.dagversion }}
        uses: dagger/dagger-for-github@v6
        with:
          verb: develop
          module: gotest/examples/go
          version: ${{ matrix.dagversion }}
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Dagger Call on Module 📦 with Dagger ${{ matrix.dagversion }}
        uses: dagger/dagger-for-github@v6
        with:
          verb: call
          module: gotest
          version: ${{ matrix.dagversion }}
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Dagger Call on Test Module 🧪 with Dagger ${{ matrix.dagversion }}
        uses: dagger/dagger-for-github@v6
        with:
          verb: call
          module: gotest/tests
          version: ${{ matrix.dagversion }}
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Dagger Call on Test Examples/Go Module 📄 with Dagger ${{ matrix.dagversion }}
        uses: dagger/dagger-for-github@v6
        with:
          verb: call
          module: gotest/examples/go
          version: ${{ matrix.dagversion }}
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  golangci-lint:
    strategy:
      matrix:
        go: ["1.22"]
    name: GolangCI-Lint for gotest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}

      # Dagger main module 📦 (develop & golang ci-lint)
      - name: Dagger Develop on Module 📦 gotest with Dagger ${{ matrix.dagversion }}
        uses: dagger/dagger-for-github@v6
        with:
          verb: develop
          module: gotest
          version: ${{ matrix.dagversion }}
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Install golangci-lint using curl
      - name: Install golangci-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s latest
          sudo mv ./bin/golangci-lint /usr/local/bin/golangci-lint

      - name: Run golangci-lint on gotest 📦
        run: |
          golangci-lint run --config=../.golangci.yml --verbose

      # Dagger test module 🧪 (develop & golang ci-lint)
      - name: Dagger Develop on Module tests 🧪 gotest with Dagger ${{ matrix.dagversion }}
        uses: dagger/dagger-for-github@v6
        with:
          verb: develop
          module: gotest/tests
          version: ${{ matrix.dagversion }}
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Run golangci-lint on gotest/tests 🧪
        run: |
          cd tests
          ls -ltrah
          golangci-lint run --config=../../.golangci.yml --verbose

      # Dagger examples (go) module 📄 (develop & golang ci-lint)
      - name: Dagger Develop on Module Examples/Go 📄 gotest with Dagger ${{ matrix.dagversion }}
        uses: dagger/dagger-for-github@v6
        with:
          verb: develop
          module: gotest/examples/go
          version: ${{ matrix.dagversion }}
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Run golangci-lint on gotest/examples/go 📄 (develop & golang ci-lint)
        run: |
          cd examples/go
          ls -ltrah
          golangci-lint run --config=../../../.golangci.yml --verbose

  gotest-test:
    strategy:
      matrix:
        go: ["1.22"]
        dagversion: [0.13.7]
    needs: [dagger-linter, golangci-lint]
    name: Run Tests 🧪 in gotest on ${{ matrix.go }} with Dagger ${{ matrix.dagversion }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
      - name: Dagger Develop on Module 📦 with Dagger ${{ matrix.dagversion }}
        uses: dagger/dagger-for-github@v6
        with:
          verb: develop
          module: gotest
          version: ${{ matrix.dagversion }}
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Dagger Develop on Test Module 🧪 with Dagger ${{ matrix.dagversion }}
        uses: dagger/dagger-for-github@v6
        with:
          verb: develop
          module: gotest/tests
          version: ${{ matrix.dagversion }}
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Running Tests 💣 in gotest on ${{ matrix.go }} with Dagger ${{ matrix.dagversion }}
        uses: dagger/dagger-for-github@v6
        with:
          verb: call
          args: test-all
          module: gotest/tests
          version: ${{ matrix.dagversion }}
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  gotest-recipes-go:
    strategy:
      matrix:
        go: ["1.22"]
        dagversion: [0.13.7]
    needs: [dagger-linter, golangci-lint]
    name: Run recipes 🥗 in gotest/examples/go on ${{ matrix.go }} with Dagger ${{ matrix.dagversion }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.22"
      - name: Dagger Develop on Module Examples 📄
        uses: dagger/dagger-for-github@v6
        with:
          verb: develop
          module: gotest/examples/go
          version: ${{ env.DAGGER_VERSION_EXAMPLES_GO }}
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Running Recipes all recipes 💣 in gotest/examples/go
        uses: dagger/dagger-for-github@v6
        with:
          verb: call
          args: all-recipes
          module: gotest/examples/go
          version: ${{ env.DAGGER_VERSION_EXAMPLES_GO }}
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
