---
name: Go lint
on:
  push:
    branches:
      - main
      - master
  pull_request:

permissions:
  contents: read
  pull-requests: read
  checks: write

jobs:
  golangci:
    strategy:
      matrix:
        go: ['1.22']
        os: [ubuntu-latest, macos-latest, windows-latest]
        module: [gotest]
    name: Lint ${{ matrix.module }} on ${{ matrix.os }} with Go ${{ matrix.go }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
      - name: Set up module
        run: cd ${{ matrix.module }}
      - name: golangci-lint on Dagger module
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.58
          working-directory: ${{ matrix.module }}/dagger
      - name: golangci-lint on Dagger test module
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.58
          working-directory: ${{ matrix.module }}/tests/dagger
