---
name: brew CI 🧹
on:
    push:
        branches:
            - main
            - master
        paths:
            - brew/**/*.go
    pull_request:
        paths:
            - brew/**/*.go
    workflow_dispatch:

permissions:
    contents: read
    pull-requests: read
    checks: write

defaults:
    run:
        working-directory: brew

jobs:
    linter:
        strategy:
            matrix:
                go: ['1.22']
                dagversion: [0.11.6, 0.11.7, 0.11.8, 0.11.9]
        name: Lint brew on ${{ matrix.os }} with Dagger ${{ matrix.dagversion }}
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-go@v5
              with:
                  go-version: ${{ matrix.go }}
            - name: Dagger Develop on Module 📦 with Dagger ${{ matrix.dagversion }}
              uses: dagger/dagger-for-github@v5
              with:
                  verb: develop
                  module: brew
                  version: ${{ matrix.dagversion }}
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            - name: Dagger Develop on Test Module 🧪 with Dagger ${{ matrix.dagversion }}
              uses: dagger/dagger-for-github@v5
              with:
                  verb: develop
                  module: brew/tests
                  version: ${{ matrix.dagversion }}
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            - name: Dagger Call on Module with Dagger ${{ matrix.dagversion }}
              uses: dagger/dagger-for-github@v5
              with:
                  verb: call
                  module: brew
                  version: ${{ matrix.dagversion }}
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            - name: Dagger Call on Test Module 🧪 with Dagger ${{ matrix.dagversion }}
              uses: dagger/dagger-for-github@v5
              with:
                  verb: call
                  module: brew/tests
                  version: ${{ matrix.dagversion }}
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    golangci-lint:
        strategy:
            matrix:
                go: ['1.22']
        name: GolangCI-Lint for brew
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-go@v5
              with:
                  go-version: ${{ matrix.go }}
            - name: Dagger Develop on Module 📦 brew with Dagger ${{ matrix.dagversion }}
              uses: dagger/dagger-for-github@v5
              with:
                  verb: develop
                  module: brew
                  version: ${{ matrix.dagversion }}
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            - name: Run golangci-lint on brew 📦
              uses: golangci/golangci-lint-action@v6
              with:
                  version: v1.58
                  args: --config .golangci.yml ./brew/dagger
            - name: Dagger Develop on Module tests 🧪 brew with Dagger ${{ matrix.dagversion }}
              uses: dagger/dagger-for-github@v5
              with:
                  verb: develop
                  module: brew/tests
                  version: ${{ matrix.dagversion }}
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            - name: Run golangci-lint on brew/tests 🧪
              uses: golangci/golangci-lint-action@v6
              with:
                  version: v1.58
                  args: --config .golangci.yml ./brew/tests/dagger

    module-test:
        strategy:
            matrix:
                go: ['1.22']
                dagversion: [0.11.6, 0.11.7, 0.11.8, 0.11.9]
        needs: [linter, golangci-lint]
        name: Run Tests 🧪 in brew on ${{ matrix.os }} with Dagger ${{ matrix.dagversion }}
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-go@v5
              with:
                  go-version: ${{ matrix.go }}
            - name: Dagger Develop on Module 📦 with Dagger ${{ matrix.dagversion }}
              uses: dagger/dagger-for-github@v5
              with:
                  verb: develop
                  module: brew
                  version: ${{ matrix.dagversion }}
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            - name: Dagger Develop on Test Module 🧪 with Dagger ${{ matrix.dagversion }}
              uses: dagger/dagger-for-github@v5
              with:
                  verb: develop
                  module: brew/tests
                  version: ${{ matrix.dagversion }}
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            - name: Running Tests 💣 in brew on ${{ matrix.os }} with Dagger ${{ matrix.dagversion }}
              uses: dagger/dagger-for-github@v5
              with:
                  verb: call
                  args: test-all
                  module: brew/tests
                  version: ${{ matrix.dagversion }}
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
