---
name: Dagger Modules Lint
on:
  push:
    branches:
      - main
      - master
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: read
  checks: write

jobs:
  golangci:
    strategy:
      matrix:
        go: ['1.22']
        dagversion: [0.11.6, 0.11.7]
        module: [gotest]
    name: Lint ${{ matrix.module }} on ${{ matrix.os }} with Dagger ${{ matrix.dagversion }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
      - name: Dagger Develop
        uses: dagger/dagger-for-github@v5
        with:
          verb: develop
          module: ${{ matrix.module }}
          version: ${{ matrix.dagversion }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Dagger Call
        uses: dagger/dagger-for-github@v5
        with:
          verb: call
          module: ${{ matrix.module }}
          version: ${{ matrix.dagversion }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup GolangCI-Lint
        run: cd ${{ matrix.module }}
      - name: Run golangci-lint on module ${{ matrix.module }}
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.58
          working-directory: ${{ matrix.module }}/dagger
          args: --config=${{ github.workspace }}/.golangci.yml
      - name: Run golangci-lint on module ${{ matrix.module }}/tests
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.58
          working-directory: ${{ matrix.module }}/tests/dagger
          args: --config=${{ github.workspace }}/.golangci.yml
