---
name: Publish Dagger Modules 🚀

on:
  workflow_dispatch:
  push:
    tags:
      - '*/v*.*.*'

env:
  GO_VERSION: ~1.22
  DAG_VERSION: 0.12.4

jobs:
  detect-and-publish-modules:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up environment
        run: |
          sudo apt-get update
          sudo apt-get install jq

      - name: Install Dagger CLI
        run: |
          curl -L https://dl.dagger.io/dagger/install.sh | DAGGER_VERSION=${{ env.DAG_VERSION }} sh
          sudo mv bin/dagger /usr/local/bin/
          dagger version
          if [[ $(dagger version | grep -oP '(?<=dagger v)\S+') != "${{ env.DAG_VERSION }}" ]]; then
            echo "Installed Dagger version does not match DAG_VERSION"
            exit 1
          fi

      - name: Identify modules to publish
        id: identify-modules
        run: |
          all_modules=()
          while IFS= read -r -d '' dir; do
            if [[ -f "$dir/dagger.json" ]]; then
              module_name="${dir#./}"
              all_modules+=("$module_name")
            fi
          done < <(find . -maxdepth 1 -type d -print0)

          modules_to_publish=()
          if [[ "${{ github.event_name }}" == "push" ]]; then
            tag="${{ github.ref_name }}"
            module_from_tag=$(echo "$tag" | cut -d'/' -f1)
            version_from_tag=$(echo "$tag" | cut -d'/' -f2)
            if [[ " ${all_modules[*]} " =~ " ${module_from_tag} " ]]; then
              modules_to_publish=("$module_from_tag")
            fi
          else
            for module in "${all_modules[@]}"; do
              latest_tag=$(git describe --tags --abbrev=0 --match "${module}/*" 2>/dev/null || echo "")
              if [[ $latest_tag =~ ^${module}/v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
                modules_to_publish+=("$module")
              fi
            done
          fi

          json_modules=$(printf '%s\n' "${modules_to_publish[@]}" | jq -R . | jq -sc)
          echo "modules_to_publish=$json_modules" >> $GITHUB_OUTPUT
          echo "Modules to publish: $json_modules"

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Publish modules
        env:
          MODULES: ${{ steps.identify-modules.outputs.modules_to_publish }}
        run: |
          echo "$MODULES" | jq -r '.[]' | while read -r module; do
            echo "Publishing module: $module"
            dagger_version=$(jq -r '.sdk // empty' "$module/dagger.json")
            dagger_version=${dagger_version:-$DAG_VERSION}

            echo "Publishing $module to Daggerverse"
            dagger publish -m $module
          done

      - name: Notify on failure
        if: failure()
        run: |
          echo "::error::Failed to publish one or more modules. Please check the logs for details."
