---
name: Release
on:
    push:
        branches:
            - main
            - '[0-9]+.[0-9]+.x'
    workflow_dispatch:
defaults:
    run:
        shell: bash
jobs:
    release-please:
        permissions:
            contents: write
            pull-requests: write
        runs-on: ubuntu-latest
        outputs:
            releases_created: ${{ steps.release.outputs.releases_created }}
            tag_name: ${{ steps.release.outputs.tag_name }}
        steps:
            - name: Checkout
              uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3
            - uses: google-github-actions/release-please-action@ee9822ec2c397e8a364d634464339ac43a06e042
              id: release
              with:
                  command: manifest
                  token: ${{secrets.GITHUB_TOKEN}}
                  default-branch: main
