---
name: Release Module 🚀
on:
    push:
        branches:
            - main
            - master
    workflow_dispatch:

defaults:
    run:
        shell: bash

permissions:
    contents: write
    pull-requests: write

jobs:
    release-please:
        permissions:
            contents: write
            pull-requests: write
        runs-on: ubuntu-latest
        outputs:
            releases_created: ${{ steps.release.outputs.releases_created }}
            tag_name: ${{ steps.release.outputs.tag_name }}
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Release Please
              uses: googleapis/release-please-action@v4
              id: release
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  default-branch: main
                  release-type: go
                  command: manifest

    publish-in-daggerverse:
        needs: release-please
        runs-on: ubuntu-latest
        env:
            GO_VERSION: ~1.22
            DAG_VERSION: 0.11.7
        strategy:
            matrix:
                module: [gotest]
        name: Publishing ${{ matrix.module }} in the Daggerverse 🚀
        if: ${{ needs.release-please.outputs.releases_created }}
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - name: Set up Go
              uses: actions/setup-go@v4
              with:
                  go-version: ${{ env.GO_VERSION }}
            - name: Dagger Develop on Module 📦 ${{ matrix.module }} with Dagger ${{ env.DAG_VERSION }}
              uses: dagger/dagger-for-github@v5
              with:
                  verb: develop
                  module: ${{ matrix.module }}
                  version: ${{ env.DAG_VERSION }}
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            - name: Publishing ${{ matrix.module }} in the Daggerverse 🚀
              uses: dagger/dagger-for-github@v5
              with:
                  verb: publish
                  module: ${{ matrix.module }}
                  version: ${{ env.DAG_VERSION }}
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
