name: Yaml Linter and Formatter

on:
  workflow_dispatch:
  push:
  pull_request:

permissions:
  contents: read
  pull-requests: write
  issues: write
  statuses: write

jobs:
  yaml-lint-and-format:
    name: Yaml Lint and Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: stable
          cache: true

      - name: Install yamlfmt
        run: go install github.com/google/yamlfmt/cmd/yamlfmt@latest

      - name: Run yamlfmt
        run: |
          yamlfmt -config .yamlfmt.yml
          if [[ -n $(git status --porcelain) ]]; then
            echo "YAML files need formatting. Please run 'yamlfmt' locally."
            exit 1
          fi

      - name: Lint GitHub Workflows
        uses: karancode/yamllint-github-action@v2.1.1
        with:
          yamllint_config_filepath: .yamllint.yml
          yamllint_file_or_dir: .github/workflows
          yamllint_strict: true
          yamllint_comment: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Lint GitHub Config Files
        uses: karancode/yamllint-github-action@v2.1.1
        with:
          yamllint_config_filepath: .yamllint.yml
          yamllint_file_or_dir: .github
          yamllint_strict: true
          yamllint_comment: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Lint Root YAML Files
        uses: karancode/yamllint-github-action@v2.1.1
        with:
          yamllint_config_filepath: .yamllint.yml
          yamllint_file_or_dir: .
          yamllint_strict: true
          yamllint_comment: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
