name: YAML Lint

on:
  workflow_dispatch:
  push:
  pull_request:

permissions:
  contents: read
  pull-requests: write
  issues: write
  statuses: write

jobs:
  yaml-lint:
    name: YAML Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Lint GitHub Workflows
        id: lint-workflows
        uses: ibiqlik/action-yamllint@v3.1.1
        with:
          config_file: .yamllint.yml
          file_or_dir: .github/workflows/
          format: github
          strict: false

      - name: Lint GitHub Config
        id: lint-github
        uses: ibiqlik/action-yamllint@v3.1.1
        with:
          config_file: .yamllint.yml
          file_or_dir: .github/
          format: github
          strict: false

      - name: Lint Root YAML Files
        id: lint-root
        uses: ibiqlik/action-yamllint@v3.1.1
        with:
          config_file: .yamllint.yml
          file_or_dir: .
          format: github
          strict: false
          exclude: |
            **/testdata/**/*.yaml
            **/testdata/**/*.yml

      - name: Upload Lint Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: yamllint-results
          path: |-
            ${{ steps.lint-workflows.outputs.logfile }}
            ${{ steps.lint-github.outputs.logfile }}
            ${{ steps.lint-root.outputs.logfile }}
