name: YAML Lint

on:
  workflow_dispatch:
  push:
  pull_request:

permissions:
  contents: read
  pull-requests: write
  issues: write
  statuses: write

jobs:
  yaml-lint:
    name: YAML Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Lint Workflows
        uses: ibiqlik/action-yamllint@v3
        with:
          file_or_dir: .github/workflows/
          config_file: .yamllint.yml
          strict: true
          format: github

      - name: Lint GitHub Config
        uses: ibiqlik/action-yamllint@v3
        with:
          file_or_dir: .github/
          config_file: .yamllint.yml
          strict: true
          format: github

      - name: Lint Root YAML Files
        uses: ibiqlik/action-yamllint@v3
        with:
          file_or_dir: .
          config_file: .yamllint.yml
          strict: true
          format: github

      - name: Upload Lint Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: yamllint-results
          path: |
            ${{ steps.yaml-lint-workflows.outputs.logfile }}
            ${{ steps.yaml-lint-config.outputs.logfile }}
            ${{ steps.yaml-lint-root.outputs.logfile }}
