---
name: YAML Lint and Format
on:
  workflow_dispatch:
  push:
  pull_request:
permissions:
  contents: read
  pull-requests: write
  issues: write
  statuses: write
jobs:
  yaml-lint-and-format:
    name: YAML Lint and Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install yamllint
        run: |
          pip install yamllint==1.35.1

      - name: Install yamlfmt
        run: |
          curl -L https://github.com/google/yamlfmt/releases/download/v0.14.0/yamlfmt_0.14.0_Linux_x86_64.tar.gz | tar xz
          sudo mv yamlfmt /usr/local/bin/

      - name: Check YAML Formatting with yamlfmt
        run: |
          yamlfmt -conf .yamlfmt.yml -lint
        # If you want the action to fail on formatting issues, keep the exit code
        continue-on-error: false

      - name: Lint YAML Files with yamllint
        id: yamllint
        run: |
          yamllint -c .yamllint.yml . | tee yamllint.log
          if [ "${PIPESTATUS[0]}" -ne 0 ]; then
            exit 1
          fi

      - name: Upload Lint Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: yamllint-results
          path: yamllint.log